# Generated by Django 4.1.1 on 2022-09-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0005_post_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=10)),
            ],
        ),
    ]
