# Generated by Django 4.1.1 on 2022-09-24 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0007_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indgredient1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogApp.ingredients')),
            ],
        ),
    ]
