# Generated by Django 4.1.1 on 2022-09-24 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0008_dishes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dishes',
        ),
        migrations.DeleteModel(
            name='Ingredients',
        ),
    ]
